import {Flex, Text} from "@chakra-ui/react"
import Head from "next/head"
import Image from "next/image"
import {useRouter} from "next/router"
import styles from "../styles/Home.module.css"

export default function Home() {
	const router = useRouter()
	return (
		<Flex
			minH='calc(100vh - 80px)'
			width='100%'
			bgColor='whiteAlpha.300'
			flexDir='column'
			overflow='hidden'>
			<Head>
				<title>Stop and Wait</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Flex
				onClick={() => router.push("error-free")}
				cursor='pointer'
				minH='calc(50vh - 40px)'
				backgroundColor='#21BF73'
				width='100%'
				justifyContent='center'
				alignItems='center'
				transition='all 300ms ease-in-out'
				_hover={{
					transform: "scaleX(1.1)",
				}}>
				<Text
					fontFamily='Open Sans'
					fontSize='42px'
					fontWeight='bold'
					color='white'>
					Error Free
				</Text>
			</Flex>
			<Flex overflow='hidden' minH='calc(50vh - 40px)' width='100%'>
				<Flex
					onClick={() => router.push("lost-ack")}
					cursor='pointer'
					justifyContent='center'
					alignItems='center'
					transition='all 300ms ease-in-out'
					_hover={{
						transform: "scaleX(1.1)",
					}}
					width='50%'
					minH='100%'
					backgroundColor='#FC9918'>
					<Text
						fontFamily='Open Sans'
						fontSize='42px'
						fontWeight='bold'
						color='white'>
						Lost Ack
					</Text>
				</Flex>
				<Flex
					onClick={() => router.push("lost-frame")}
					justifyContent='center'
					alignItems='center'
					transition='all 300ms ease-in-out'
					_hover={{
						transform: "scaleX(1.1)",
					}}
					width='50%'
					minH='100%'
					backgroundColor='#FFE400'
					cursor='pointer'>
					<Text
						fontFamily='Open Sans'
						fontSize='42px'
						fontWeight='bold'
						color='white'>
						Lost Frame
					</Text>
				</Flex>
			</Flex>
		</Flex>
	)
}
